version: "3"
services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  angular-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
