apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: exp-5-frontend
        ports:
        - containerPort: 5173
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
