apiVersion: v1
kind: Service
metadata:
  name: social-media-service
spec:
  selector:
    app: social-media           # This must match your deployment's pod labels
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000               # Port exposed by the service
      targetPort: 8000         # Port on the container
